
name: Publish Website to Web Hosting
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Sync files
      uses: sand4rt/ftp-deployer@v1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: ${{secrets.FTP_SERVER_DIR}}
